#!/usr/bin/env bash
# Build backend/.env for bare-metal (phase 1) deploy from phase-1 secrets.
# Does not overwrite an existing backend/.env unless FORCE=1.
#
# Usage (on the VM, after phase 1):
#   cd ~/combined-intelligence
#   git pull
#   sudo env PRIMARY_HOST=20.157.90.21 bash infra/scripts/generate-bare-metal-env.sh
#
# Then edit backend/.env: add GOOGLE_*, S3_*, VAPID_*, SYNTHESIS_BACKEND, etc.
# Copy infra/.env from your workstation or infra/.env.example + UBUNTU_STATIC_IP.
set -euo pipefail

_bootstrap_entry="${BASH_SOURCE[0]}"
# shellcheck source=bootstrap-ubuntu-init.sh
source "$(dirname "$_bootstrap_entry")/bootstrap-ubuntu-init.sh"
# shellcheck source=bootstrap-ubuntu-common.sh
source "${BOOTSTRAP_SCRIPT_DIR}/bootstrap-ubuntu-common.sh"

require_root
[[ -f "$SECRETS_FILE" ]] || die "Missing ${SECRETS_FILE} — run phase 1 first."
# shellcheck disable=SC1090
source "$SECRETS_FILE"

PRIMARY_HOST="${PRIMARY_HOST:-}"
if [[ -z "$PRIMARY_HOST" ]]; then
  die "Set PRIMARY_HOST (VM public IP or domain), e.g. sudo env PRIMARY_HOST=20.157.90.21 bash $0"
fi

USE_HTTPS="${USE_HTTPS:-0}"
if [[ "$USE_HTTPS" == "1" ]]; then
  BASE_URL="https://${PRIMARY_HOST}"
  COOKIE_SECURE="True"
  ALLOWED_ORIGINS='["https://'"${PRIMARY_HOST}"'"]'
  GOOGLE_REDIRECT_URI="${BASE_URL}/api/auth/google/callback"
else
  BASE_URL="http://${PRIMARY_HOST}"
  COOKIE_SECURE="False"
  ALLOWED_ORIGINS='["http://'"${PRIMARY_HOST}"'"]'
  GOOGLE_REDIRECT_URI="${BASE_URL}/api/auth/google/callback"
fi

ENV_FILE="${REPO_DIR}/backend/.env"
if [[ -f "$ENV_FILE" && "${FORCE:-0}" != "1" ]]; then
  die "${ENV_FILE} already exists. Edit it or run with FORCE=1 to replace."
fi

mkdir -p "$(dirname "$ENV_FILE")"
cat > "$ENV_FILE" <<EOF
# Generated by infra/scripts/generate-bare-metal-env.sh — review before phase 2.
ENVIRONMENT=production

BASE_URL=${BASE_URL}
COOKIE_DOMAIN=
COOKIE_SECURE=${COOKIE_SECURE}
ALLOWED_ORIGINS=${ALLOWED_ORIGINS}

JWT_SECRET=${JWT_SECRET}
JWT_ALGORITHM=HS256

# Add real values (see infra/.env.example). Redirect URI must match Google Console.
GOOGLE_CLIENT_ID=your-client-id.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET=your-client-secret
GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}

MONGO_URL=mongodb://ci_app:${MONGO_APP_PASSWORD}@127.0.0.1:27017/${MONGO_DB}?authSource=${MONGO_DB}
MONGO_DB=${MONGO_DB}
REDIS_URL=redis://:${REDIS_PASSWORD}@127.0.0.1:6379/0
QDRANT_URL=http://127.0.0.1:6333

# Scaleway S3 — required by Settings()
S3_ENDPOINT_URL=https://s3.fr-par.scw.cloud
S3_REGION=fr-par
S3_ACCESS_KEY=change-me
S3_SECRET_KEY=change-me
S3_BUCKET=bm-ai
S3_PREFIX=combinedintelligence

GCP_PROJECT=change-me
GCP_ZONE=us-central1-a
GCP_VM_INSTANCE=ci-ollama-inference

VAPID_PRIVATE_KEY=change-me
VAPID_PUBLIC_KEY=change-me
VAPID_CLAIMS_SUB=mailto:desk@combinedintelligence.us

SYNTHESIS_BACKEND=tpu_jetstream

ANTHROPIC_API_KEY=
OPENAI_API_KEY=
EOF

chown "${DEPLOY_USER}:${DEPLOY_USER}" "$ENV_FILE" 2>/dev/null || true
chmod 600 "$ENV_FILE"

log "Wrote ${ENV_FILE}"
echo ""
echo "Edit before phase 2:"
echo "  - GOOGLE_CLIENT_ID / GOOGLE_CLIENT_SECRET (redirect: ${GOOGLE_REDIRECT_URI})"
echo "  - S3_ACCESS_KEY / S3_SECRET_KEY"
echo "  - VAPID_* keys"
echo "  - GCP_PROJECT (if using Ollama VM endpoints)"
echo ""
echo "Create ${REPO_DIR}/infra/.env for TPU (UBUNTU_STATIC_IP=${PRIMARY_HOST}, TPU_*, etc.)"
echo ""
echo "Then:"
echo "  sudo env PRIMARY_HOST=${PRIMARY_HOST} bash ${REPO_DIR}/infra/scripts/bootstrap-ubuntu-phase2-app.sh"
